### ISSUE TITLE
Monster และอุปสรรคภายในเกม

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#10]

**Comment by Unlxii** [comment]
obstacles https://drive.google.com/drive/folders/1Ai-IdZHPrFENTnb-fyRrQ23BZ0MabhDg?usp=sharing
-map 2-

**Comment by Unlxii** [comment]
Boss https://drive.google.com/drive/folders/1sofTTwln8_mKSEH3tI3-jAR5zhwjBwhA?usp=sharing 
-map 2-

**Comment by Unlxii** [comment]
> obstacles https://drive.google.com/drive/folders/1Ai-IdZHPrFENTnb-fyRrQ23BZ0MabhDg?usp=sharing -map 2-

แก้ขนาด obstacles pen red

**Comment by Unlxii** [comment]
obstacles https://drive.google.com/drive/folders/110YkIXmGEAdP2R8I3c5MTseNNYloZ7uw?usp=sharing
-map 1-
