### ISSUE TITLE
เกมดีไซน์ของด่านแรก

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#12]
เกี่ยวกับภาพประกอบฉาก แท่นในการกระโดดและเสียงเพลงประกอบฉากต่างๆ

**Comment by Unlxii** [comment]
background -map 1-  https://drive.google.com/drive/folders/1HJUQ6VXHDgwi6V5H6kwfEAMkZuGB8L0Q?usp=sharing

**Comment by Unlxii** [comment]
background -map 2- https://drive.google.com/drive/folders/1Jb9AAIvJzBktArwotq5x8jsP7tzVFtBk?usp=sharing

**Comment by monophoto** [comment]
(https://i.imgur.com/c8mmRWA.png)

เตียงปกติ

**Comment by monophoto** [comment]
(https://i.imgur.com/7akEVBh.png) 
ปลั๊กไฟ 

(https://i.imgur.com/vRQAxPH.png)
ไฟพุ่งกระโดด

**Comment by monophoto** [comment]
![](https://i.imgur.com/ZyWfRGP.png)

ขวดน้ำแตก

![](https://i.imgur.com/tMEwrja.png)

![](https://i.imgur.com/rrCGwa7.png)

**Comment by monophoto** [comment]
![](https://i.imgur.com/0YeT2ml.png)
ตู้เย็นเลื่อนซ้ายขวา

**Comment by monophoto** [comment]
Cut scene https://www.canva.com/design/DAFMHl5D0Bs/jrSaPv-v5poFVsbcF7usGQ/edit?utm_content=DAFMHl5D0Bs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by monophoto** [comment]
![](https://i.imgur.com/aLvVapC.png)
 หม้อน้ำร้อน

**Comment by monophoto** [comment]
![](https://i.imgur.com/cB8F09I.png)



![](https://i.imgur.com/x3dKuoJ.png)

![](https://i.imgur.com/1SnjN2r.png)
