### ISSUE TITLE
เกมดีไซน์ของด่านที่สอง

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#13]

**Comment by Unlxii** [comment]
background -map 2- https://drive.google.com/drive/folders/1Jb9AAIvJzBktArwotq5x8jsP7tzVFtBk?usp=sharing

**Comment by Unlxii** [comment]
ปากกาสีแดง 
![pen red](https://user-images.githubusercontent.com/87744652/189978647-d2d8a59d-608d-4f4e-8672-89a526235f7e.png)

**Comment by Unlxii** [comment]
ปากกาสีแดง แบบหัก
![pen red back](https://user-images.githubusercontent.com/87744652/189978779-63129fab-4f2f-4e29-bab1-529a8a7d410f.png)
![pen red front](https://user-images.githubusercontent.com/87744652/189978786-b6050898-b1a0-4387-984b-c0a2726b4b64.png)

**Comment by Unlxii** [comment]
ช็อค แบบเลื่อน
![ช็อค](https://user-images.githubusercontent.com/87744652/189978923-ff1c20e6-7800-42a8-b059-23d06b1ab05d.png)

**Comment by Unlxii** [comment]
แปรงลบกระดาน แบบกระโดด
![แปรงลบกระดาน](https://user-images.githubusercontent.com/87744652/189978988-99752a78-d675-4db4-b08b-71fd2fe6bc99.png)

**Comment by Unlxii** [comment]
โต๊ะ
![table](https://user-images.githubusercontent.com/87744652/189979832-6c2961fa-fc60-4d1b-bca6-6b02059e4a25.png)

**Comment by Unlxii** [comment]
ไม้ตาย โดนตาย
![ไม้ตี](https://user-images.githubusercontent.com/87744652/189980602-f615ee75-9049-4e8e-8388-87cacae6ea59.png)
