### ISSUE TITLE
เกมดีไซน์ด่านที่สาม

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#15]

**Comment by Unlxii** [comment]
background -map 3- https://drive.google.com/drive/folders/1wrePA-nEe5SQWgJwXow-J_o9H2mVZ0th?usp=sharing

**Comment by Unlxii** [comment]
แฟ้ม
![แฟ้ม](https://user-images.githubusercontent.com/87744652/190120471-71f8ca26-3142-45e2-bd4e-f0916cc2d6ff.png)

**Comment by Unlxii** [comment]
จอ แตก

![จอ 1](https://user-images.githubusercontent.com/87744652/190215729-e158d583-f129-475d-9d3b-e83d86125f0a.png)
![จอ 2](https://user-images.githubusercontent.com/87744652/190215740-7e274725-757d-4549-9bc9-4eaa8a448cfc.png)
![จอ 3](https://user-images.githubusercontent.com/87744652/190215744-aa91c888-5f3f-4ce2-bb53-d282b14074b1.png)
![จอ 4](https://user-images.githubusercontent.com/87744652/190215747-1cb8b888-795e-4c5a-994f-8e998cc0a725.png)

**Comment by Unlxii** [comment]
ตู้เลื่อน
![ตู้](https://user-images.githubusercontent.com/87744652/190127902-055993f8-5145-4218-b926-e0c350a83869.png)

**Comment by Unlxii** [comment]
เก้าอี้ กระโดด 
![เก้าอี้](https://user-images.githubusercontent.com/87744652/190129592-1dc9a4a2-0281-4085-b401-95ca854a21bb.png)

**Comment by Unlxii** [comment]
หมุด ตาย
![หมุด](https://user-images.githubusercontent.com/87744652/190132613-081944b9-6892-4708-b52e-d0faf47e8638.png)

**Comment by Unlxii** [comment]
background 3
![background 3](https://user-images.githubusercontent.com/87744652/190900030-1693ab1c-957c-4ba7-8c09-631e74bf9523.png)

**Comment by Unlxii** [comment]
![ที่ทำงาน](https://user-images.githubusercontent.com/87744652/191269301-c48b1b9c-ae9c-487a-9f2f-9a6aa07e9f18.png)

**Comment by Unlxii** [comment]
![ที่ทำงาน](https://user-images.githubusercontent.com/87744652/191271891-5a002790-2a4e-47e5-bdda-08b0673634a5.png)
