### ISSUE TITLE
เกมดีไซน์ด่านที่สี่

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#16]

**Comment by Unlxii** [comment]
background - map 4 - https://drive.google.com/drive/folders/1_nqnBkOYPer_Sv8VATHQAx5PTjl_FmRf?usp=sharing

**Comment by Unlxii** [comment]
รถเมล์
![รถเมล์](https://user-images.githubusercontent.com/87744652/190181224-b9cb10c6-3786-4655-bbd5-8f963d976259.png)

**Comment by Unlxii** [comment]
รถไฟฟ้า เลื่อน
![รถไฟฟ้า](https://user-images.githubusercontent.com/87744652/190216419-91b0fd5e-f8c4-44e0-b90c-cec257c64e69.png)

**Comment by Unlxii** [comment]
เป๋าตังมีเงิน กระโดด 
![เงิน](https://user-images.githubusercontent.com/87744652/190220407-f222e673-e157-4a76-996c-1a128bccebe7.png)

**Comment by Unlxii** [comment]
บัตรเครดิต หัก
![card](https://user-images.githubusercontent.com/87744652/190222579-db5390ea-c1b5-4bd6-83be-4df8adf245c7.png)
![card front](https://user-images.githubusercontent.com/87744652/190222598-53ad95cd-239b-4ca5-8c08-561dd5589e6e.png)
![card back](https://user-images.githubusercontent.com/87744652/190222619-f7fbaba2-bca4-42dc-b8f5-2f4bbf792164.png)

**Comment by Unlxii** [comment]
พัสดุบวกภาษี โดนตาย
![พัสดุบวกภาษี](https://user-images.githubusercontent.com/87744652/190227547-42ac462e-086a-4a0e-89b5-ba7464e153c5.png)

**Comment by Unlxii** [comment]
background 4 แก้
![background 4](https://user-images.githubusercontent.com/87744652/190899922-dd0d1f35-d10b-47a7-ad2f-a8eb535a78a7.png)

**Comment by Unlxii** [comment]
![เมือง](https://user-images.githubusercontent.com/87744652/191302212-9af3d66f-4959-4d99-b129-99c74c88882e.png)
