### ISSUE TITLE
คัทซีนสำหรับเปลี่ยนฉาก

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#17]

**Comment by monophoto** [comment]
https://www.canva.com/design/DAFMHl5D0Bs/sLS36cXl6X13I_6zMBtSJw/view?utm_content=DAFMHl5D0Bs&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by monophoto** [comment]
https://www.canva.com/design/DAFMHl5D0Bs/jrSaPv-v5poFVsbcF7usGQ/edit?utm_content=DAFMHl5D0Bs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by monophoto** [comment]
เรียงตามด่านเลยนะ สงสัยหรืออยากแก้ เม้นเพิ่มมาได้

**Comment by Whale56** [comment]
โอเคกำลังทำระบบอยู่ บัคนิดหน่อย น่าจะเสร็จก่อนวันจันทร์ ไม่ก็ภายในวันจันทร์

**Comment by Phummyphum** [comment]
เกิดปัญหาด้านระบบทำให้ไม่สามารถใส่คัทซีนเข้าไปในเกมได้ด้วยข้อจำกัดโปรแกรม
