### ISSUE TITLE
ตัวละครหลัก และมอนเตอร์ตัวอื่น

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#18]

**Comment by Unlxii** [comment]
character  https://drive.google.com/drive/folders/1LJ-N9_GjOzFNJtLANi5RHUN1nhAZjlLF?usp=sharing

**Comment by Unlxii** [comment]
รอแก้ไข้ตัวละครหลัก

**Comment by Unlxii** [comment]
![ตัวหลัก (1)](https://user-images.githubusercontent.com/87744652/189957607-a2586b1d-406c-4076-8069-3accc293540b.gif)
พร้อมเงา

**Comment by Unlxii** [comment]
![image](https://user-images.githubusercontent.com/87744652/189957718-c7053e8d-fa37-4ad6-a558-1285e36530b5.png)
ตัวหลัก 2 เฟรม

**Comment by Unlxii** [comment]
2เฟรม พร้อมเงา
![ตัวหลัก (1)](https://user-images.githubusercontent.com/87744652/189957885-8d0e89be-4f12-4fbe-8034-cbed2a6de407.png)

**Comment by Unlxii** [comment]
2 เฟรม ไม่มีเงา 
![ตัวหลัก](https://user-images.githubusercontent.com/87744652/189958246-11b665ec-2c35-49f8-8f3b-06fc60114490.png)

**Comment by Unlxii** [comment]
2เฟรม ไม่มีเงา
![ตัวหลัก (2)](https://user-images.githubusercontent.com/87744652/189958623-0fa8eb92-d050-4270-86fb-3a65e3e3e9a7.png)

**Comment by Unlxii** [comment]
![ตัวหลัก (1) (1)](https://user-images.githubusercontent.com/87744652/189970766-d8d39163-0a6f-4ab8-9362-85a234e5fe4f.png)
เงาตัวหลัก 2 เฟรม

**Comment by Unlxii** [comment]
ตัวละคร แบบที่2 2เฟรม
![model map 3](https://user-images.githubusercontent.com/87744652/190073904-aa30a330-1f61-47da-b4a3-b55affb3aa36.png)

**Comment by Unlxii** [comment]
ตัวละคร แบบที่ 3 เงา 2 เฟรม
![model เงา แบบ 2](https://user-images.githubusercontent.com/87744652/190074744-a3d43535-eff7-46b1-8e02-eb64a1ca8b37.png)
