### ISSUE TITLE
ตัวละครที่เราใช้เล่น

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#19]

**Comment by Unlxii** [comment]
เพิ่มเติม ตัวละครหลัก
![model ตัว 1](https://user-images.githubusercontent.com/87744652/190209276-db2db283-f723-477e-a35e-c9da7df74229.png)
![model ตัว 1 1](https://user-images.githubusercontent.com/87744652/190209261-a4fdd843-698f-4c2d-800f-c8724c57ad19.png)
![model ตัว 1 2](https://user-images.githubusercontent.com/87744652/190209271-87d15ef0-c9e8-4737-b7e3-f64435f021d6.png)

**Comment by Unlxii** [comment]
เพิ่มเติม เงา ตัวละครหลัก
![เงา 1](https://user-images.githubusercontent.com/87744652/190210270-9d89363f-a68d-4bbc-9eb9-f1d8f2e0d5f8.png)
![เงา 1 1](https://user-images.githubusercontent.com/87744652/190210260-92a02e33-206e-40e8-a902-bae9da90e98b.png)
![เงา 1 2](https://user-images.githubusercontent.com/87744652/190210265-16c830de-ac1e-4eb3-a3a9-84e142854097.png)

**Comment by Unlxii** [comment]
เพิ่มเติม ตัวละครหลัก --

![model](https://user-images.githubusercontent.com/87744652/190214022-b11493a5-672b-440c-8ec3-a4e62ff87113.png)
![modell](https://user-images.githubusercontent.com/87744652/190214027-99a36e4e-6075-4ae0-a1f6-2d36717c8c56.png)
![modelll](https://user-images.githubusercontent.com/87744652/190214032-4c256b51-e8ff-4f6d-906f-262c544313da.png)

**Comment by Unlxii** [comment]
เพิ่มเติม ตัวละครหลัก เงา --

![เงา model](https://user-images.githubusercontent.com/87744652/190214108-334efc1e-4425-45d6-aea1-02ac66de4f60.png)
![เงา modell](https://user-images.githubusercontent.com/87744652/190214114-b3a38feb-f247-4b2f-8761-1c8821469e46.png)
![เงา modelll](https://user-images.githubusercontent.com/87744652/190214118-b0d88ba0-8535-4681-bb93-bc36e2bce4dc.png)
