### ISSUE TITLE
ฉากของด่านที่ 1 และ 2 ที่ต้องการแก้

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#20]

**Comment by Unlxii** [comment]
เตียง
![เตียง](https://user-images.githubusercontent.com/87744652/190115320-7b5d373a-c66f-4b89-803c-bf0c01803b16.png)

**Comment by Unlxii** [comment]
ปลั๊กไฟ กระโดด
![ปลั๊กไฟ](https://user-images.githubusercontent.com/87744652/190115429-0e4dd779-8918-4647-982b-928a1b40eb98.png)

**Comment by Unlxii** [comment]
โซฟา เลื่อน
![โซฟา](https://user-images.githubusercontent.com/87744652/190117117-28ec7ab4-2bd4-43a0-be02-62b2073717a7.png)

**Comment by Unlxii** [comment]
หม้อโดน ตาย 

![หม้อ 1](https://user-images.githubusercontent.com/87744652/190214836-f64114b8-a4f7-41d1-8202-e55ec4c7a0dc.png)
![หม้อ 2](https://user-images.githubusercontent.com/87744652/190214842-b3a67326-7ecc-4684-a75e-3570e19bf000.png)
![หม้อ 3](https://user-images.githubusercontent.com/87744652/190214846-79d0798b-40fa-4cb4-9959-785cd5ced47d.png)
![หม้อ 4](https://user-images.githubusercontent.com/87744652/190214850-579a451f-8e56-4e61-80d9-dceb222d21c5.png)

**Comment by Unlxii** [comment]
![แฟ้ม2](https://user-images.githubusercontent.com/87744652/190885729-b4e6967d-dc3c-4f87-9a6c-cd5c6db898b3.png)
![แฟ้ม3](https://user-images.githubusercontent.com/87744652/190885731-b03d24df-eb82-4202-980a-da38d9bbb412.png)

**Comment by Unlxii** [comment]
![background 4](https://user-images.githubusercontent.com/87744652/190899785-9d0e2827-d2ef-452e-88c6-35200f274eca.png)
![background](https://user-images.githubusercontent.com/87744652/190899787-6b12a2e8-716e-47a9-b00a-12d7f62b4883.png)
![background 2](https://user-images.githubusercontent.com/87744652/190899789-e727ebe5-00b8-4be8-bdba-cef58aac40d2.png)
![background 3](https://user-images.githubusercontent.com/87744652/190899791-08dfa5d2-3caf-4cc1-8167-e0ae8294011b.png)

**Comment by Unlxii** [comment]
background 1 และ 2 แก้

![background 2](https://user-images.githubusercontent.com/87744652/190899829-d68bf25a-875e-4042-8938-4450299f35a7.png)
![background](https://user-images.githubusercontent.com/87744652/190899826-db24edbe-9744-49d1-ba05-986adc38fbe6.png)

**Comment by Unlxii** [comment]
![โรงเรียน](https://user-images.githubusercontent.com/87744652/191230028-3f463d0d-a49c-4011-97dc-82fcf7b34bf4.png)
![บ้าน](https://user-images.githubusercontent.com/87744652/191230035-982fd41f-caf9-481d-b749-f9d5e210dddb.png)

**Comment by Unlxii** [comment]
![บ้าน](https://user-images.githubusercontent.com/87744652/191271980-7c6ec5b9-e702-4046-8800-06ae43dafca8.png)
![โรงเรียน](https://user-images.githubusercontent.com/87744652/191271986-52c76a95-bc3a-4290-bdf0-c1cceec04841.png)
