### ISSUE TITLE
แก้ไขโค้ด

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#22]

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/105911727/193844159-ad137f78-b6b0-4a63-a014-cad4b5000764.png)
แก้โค้ดการขยับ

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/105911727/193844309-3b8f1456-fba7-4f5f-834d-f444664616d4.png)
ปรับแท่นที่โดละตายออก เพื่อให้เกมง่ายขึ้น ละทำให้มีแท่นมากขึ้นกว่าเดิม
