### ISSUE TITLE
แก้ไข Background

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#23]

**Comment by Unlxii** [comment]
![background](https://user-images.githubusercontent.com/87744652/193459615-025515e2-366b-443f-ac5e-c53d1fafaa02.png)

background

**Comment by Unlxii** [comment]
obj 
![obj 2](https://user-images.githubusercontent.com/87744652/193459638-b99b484e-1ff5-4c14-b2bb-e3a9640e6f91.png)
![obj 3](https://user-images.githubusercontent.com/87744652/193459640-ee5cad89-9eb1-4a66-ba4f-728013e901e2.png)
![obj 4](https://user-images.githubusercontent.com/87744652/193459642-2d649858-5287-4a58-8d1d-b4b50f8e4795.png)
![obj](https://user-images.githubusercontent.com/87744652/193459644-ccbe6910-0363-44c0-ac3b-038f0e0373e9.png)
![obj 6](https://user-images.githubusercontent.com/87744652/193459782-78bfab9d-eedc-4d53-ad4e-a308ea093c22.png)
