### ISSUE TITLE
ออกแบบท่าทาง

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#24]

**Comment by Unlxii** [comment]
[![image](https://user-images.githubusercontent.com/87744652/193755503-b5a1ca86-4017-4065-a76f-2c31b23f8088.png)](https://teachablemachine.withgoogle.com/models/88X2WhkMy/)

data set

**Comment by Unlxii** [comment]
https://teachablemachine.withgoogle.com/models/88X2WhkMy/

data set

**Comment by Unlxii** [comment]
จับสีแดง เคลื่อนซ้าย 
![move left](https://user-images.githubusercontent.com/87744652/193756706-b78ca553-c864-4dd8-a3e7-1b3ff59c9e27.jpg)

**Comment by Unlxii** [comment]
จับสีเขียวเคลื่อนขวา 
![move right](https://user-images.githubusercontent.com/87744652/193756777-a4933177-1134-48e4-933e-34442c567987.jpg)

**Comment by Unlxii** [comment]
with out prop 
![with out prop](https://user-images.githubusercontent.com/87744652/193769542-408922e2-5fd2-4702-a095-43a0f01eb97c.jpg)
