### ISSUE TITLE
นำเสนอ

### ISSUE THREAD

**Issue by Unlxii** [Phummyphum/cpe103-test-group-11#25]
https://drive.google.com/drive/folders/1CaSnz6CbXyC0byp3BdIF9oPpdEay3T4c?usp=sharing

**Comment by Phummyphum** [comment]
https://www.canva.com/design/DAFOFvzugLQ/Lg-kjesn-JDpcB92YLtH8g/edit?utm_content=DAFOFvzugLQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
