### ISSUE TITLE
ทำตัวละครเคลื่อน กระโดด ขยับซ้าย ขวา

### ISSUE THREAD

**Issue by Phummyphum** [Phummyphum/cpe103-test-group-11#9]

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/105911727/189453489-4de01e5c-bb88-4b36-b740-081ed2d18837.png)

![image](https://user-images.githubusercontent.com/105911727/189453470-d419836d-2ffd-4467-b6a0-d867e7d588b9.png)

ยังมีบัคในเรื่องการให้ทำตัวละครกระโดดที่บัคกับแท่นในฉาก
